name: flutter_leaf_state
description: A new Flutter package project.
version: "4.4.0-dev"
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1

  flutter_leaf_core:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.4.0-dev"
      path: ./packages/leaf_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
