name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0

  # Build Gen Plugin
  built_value: ^8.9.2
  built_collection: ^5.1.1
  json_annotation: ^4.8.1
  dart_object_extension: ^0.1.1

  # Leaf Kit Plugin
  flutter_leaf_kit:
    path: ../packages/leaf

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Build Gen Plugin
  built_value_generator: ^8.9.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  dart_object_extension_gen: ^0.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/