name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  easy_localization: ^3.0.1

  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0

  json_annotation: ^4.7.0
  built_value: ^8.4.2
  built_collection: ^5.1.1
  chopper: ^6.1.4
  http: ^0.13.5

  # Leaf Kit Plugin
  flutter_leaf_kit:
    path: ../packages/leaf

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  built_value_generator: ^8.4.2
  chopper_generator: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/