name: example
description: Flutter Leaf Kit Example App
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  # Leaf Kit Plugin (workspace에서 자동 해결)
  flutter_leaf_kit: any

  dart_object_extension: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.13.1
  built_value_generator: ^8.12.5
  dart_object_extension_gen: ^0.4.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/translations/

  fonts:
  - family: NotoSansJP
    fonts:
    - asset: assets/fonts/NotoSansJP-Thin.ttf
      weight: 100
    - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
      weight: 200
    - asset: assets/fonts/NotoSansJP-Light.ttf
      weight: 300
    - asset: assets/fonts/NotoSansJP-Regular.ttf
      weight: 400
    - asset: assets/fonts/NotoSansJP-Medium.ttf
      weight: 500
    - asset: assets/fonts/NotoSansJP-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/NotoSansJP-Bold.ttf
      weight: 700
    - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/NotoSansJP-Black.ttf
      weight: 900
