name: flutter_leaf_kit

packages:
  - example/
  - packages/**

ignore:
  - packages/**/example

scripts:
  analyze:flutter:
    run: melos exec -c 1 -- flutter analyze
    description: Analyze (All Packages)

  format:dart:
    run: melos exec -c 1 -- dart format .
    description: Formatting (All Packages)

  get:flutter:
    run: melos exec -c 1 -- flutter pub get
    description: Get packages (All Packages)

  get:pub_outdated:
    # run: bash scripts/flutter_pub_outdated.sh
    run: melos exec -c 1 -- dart pub outdated
    description: Get Flutter pub outdated