[tool.poetry]
name = "flutter_leaf_kit"
version = "0.0.1"
description = "Flutter Leaf Kit Project."
authors = ["JosephNK <nkw0608@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scripts"}]

[tool.poetry.dependencies]
python = "^3.11"
ruamel-yaml = "^0.19.1"
gitpython = "^3.1.0"
pre-commit = "^4.1.0"

[tool.poetry.scripts]
update-version = "scripts.update_version:main"
update-deps = "scripts.update_dependencies:main"
pub-outdated = "scripts.pub_outdated:main"
merge-to-main = "scripts.merge_to_main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
