name: leaf_network
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  leaf_common:
    path: ../leaf_common
  leaf_manager:
    path: ../leaf_manager

  connectivity_plus: ^3.0.3
  http: ^0.13.4
  http_parser: ^4.0.1

  chopper: ^6.1.0
  built_value: ^8.4.1
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  built_value_generator: ^8.4.1

flutter:
