name: flutter_leaf_network
description: A new Flutter package project.
version: 1.8.6
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  dio: ^5.4.2+1
  dio_intercept_to_curl: ^0.2.0

  built_value: ^8.9.2
  built_collection: ^5.1.1

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.8.6'
      path: ./packages/leaf_common
  flutter_leaf_manager:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.8.6'
      path: ./packages/leaf_manager
  flutter_leaf_store:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.8.6'
      path: ./packages/leaf_store

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Build Gen Plugin
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2

flutter:
