name: leaf_data
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  leaf_component:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_component

  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: