name: leaf_location
description: A new Flutter package project.
version: 0.0.3
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^10.1.0
  
  leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.3'
      path: ./packages/leaf_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
