name: flutter_leaf_navigation
description: A new Flutter package project.
version: 1.6.0
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  navigation_history_observer: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  page_transition: ^2.1.0

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.6.0'
      path: ./packages/leaf_common
  flutter_leaf_store:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.6.0'
      path: ./packages/leaf_store

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
