name: leaf_navigation
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_common
  leaf_bloc:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_bloc

  navigation_history_observer: ^1.1.0
  modal_bottom_sheet: ^3.0.0-pre
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
