name: flutter_leaf_component
description: A new Flutter package project.
version: "4.2.0-dev"
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_cache_manager: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  expandable_page_view: ^1.2.0
  shimmer: ^3.0.0
  photo_manager: ^3.8.3
  visibility_detector: ^0.4.0+2
  fluttertoast: ^9.0.0
  toastification: ^3.0.3
  easy_rich_text: ^2.2.0
  auto_size_text_plus: ^3.0.2
  flutter_datetime_picker_plus: ^2.2.0
  vector_graphics: ^1.1.19
  flutter_svg: ^2.2.3
  lucide_icons_flutter: ^3.1.9
  device_info_plus: ^12.3.0

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.2.0-dev"
      path: ./packages/leaf_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
