name: flutter_leaf_component
description: A new Flutter package project.
version: 1.9.15-dev
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  flutter_cache_manager: ^3.3.2
  flutter_rating_bar: ^4.0.1
  expandable_page_view: ^1.0.17
  shimmer: ^3.0.0
  photo_manager: ^3.1.1
  visibility_detector: ^0.4.0+2
  fluttertoast: ^8.2.5
  easy_rich_text: ^2.1.0
  auto_size_text: ^3.0.0

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.15-dev'
      path: ./packages/leaf_common
  flutter_leaf_manager:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.15-dev'
      path: ./packages/leaf_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
