name: flutter_leaf_kit
description: A new Flutter package project.
version: 1.1.6
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'common_1.0.2'
      path: ./packages/leaf_common
  flutter_leaf_component:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'component_1.0.2'
      path: ./packages/leaf_component
  flutter_leaf_location:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'location_1.0.0'
      path: ./packages/leaf_location
  flutter_leaf_map:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'map_1.0.0'
      path: ./packages/leaf_map
  flutter_leaf_navigation:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'navigation_1.0.0'
      path: ./packages/leaf_navigation
  flutter_leaf_manager:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'manager_1.0.0'
      path: ./packages/leaf_manager
  flutter_leaf_network:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'network_1.0.2'
      path: ./packages/leaf_network
  flutter_leaf_store:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'store_1.0.0'
      path: ./packages/leaf_store
  flutter_leaf_webview:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'webview_1.0.0'
      path: ./packages/leaf_webview

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
