name: flutter_leaf_kit
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_common
  leaf_component:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_component
  leaf_data:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_data
  leaf_firebase:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_firebase
  leaf_manager:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_manager
  leaf_navigation:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: develop
      path: ./packages/leaf_navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
