name: flutter_leaf_kit
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  leaf_bloc:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_bloc
  leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_common
  leaf_component:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_component
  leaf_device:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_devices
  leaf_file:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_file
  leaf_location:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_location
  leaf_package:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_package
  leaf_navigation:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_navigation
  leaf_network:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_network
  leaf_permission:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.2'
      path: ./packages/leaf_permission

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
