name: flutter_leaf_kit
description: A new Flutter package project.
version: "4.6.4-dev"
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_leaf_core:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_core
  flutter_leaf_component:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_component
  flutter_leaf_platform:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_platform
  flutter_leaf_route:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_route
  flutter_leaf_network:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_network
  flutter_leaf_state:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: "v4.6.4-dev"
      path: ./packages/leaf_state

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
