name: flutter_leaf_webview
description: A new Flutter package project.
version: 1.9.34-dev
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.0

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.34-dev'
      path: ./packages/leaf_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
