name: flutter_leaf_map
description: A new Flutter package project.
version: 1.0.0
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.0
  
  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'common_1.0.1'
      path: ./packages/leaf_common
  flutter_leaf_location:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '1.0.0'
      path: ./packages/leaf_location
  flutter_leaf_network:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '1.0.0'
      path: ./packages/leaf_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
