name: leaf_map
description: A new Flutter package project.
version: 0.0.5
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  
  leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.3'
      path: ./packages/leaf_common
  leaf_location:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.3'
      path: ./packages/leaf_location
  leaf_network:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: '0.0.3'
      path: ./packages/leaf_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
