name: flutter_leaf_map
description: A new Flutter package project.
version: 1.9.24-dev
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.1

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.24-dev'
      path: ./packages/leaf_common
  flutter_leaf_location:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.24-dev'
      path: ./packages/leaf_location

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
