name: flutter_leaf_common
description: A new Flutter package project.
version: 1.9.26-dev
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  provider: ^6.1.2

  collection: ^1.18.0
  easy_localization: ^3.0.7
  logger: ^2.3.0
  quiver: ^3.2.1
  string_validator: ^1.0.2

# package_info_plus (temporarily override for chewie)
dependency_overrides:
  wakelock:
    git:
      url: https://github.com/diegotori/wakelock.git
      ref: main
      path: wakelock/
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock.git
      ref: main
      path: wakelock_windows/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
