name: leaf_common
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  logger: ^2.0.2+1
  quiver: ^3.2.1
  string_validator: ^1.0.2
  shared_preferences: ^2.2.2
  app_tracking_transparency: ^2.0.4
  flutter_app_badger: ^1.5.0
  device_info_plus: ^9.1.0
  android_id: ^0.3.6
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  klc: ^0.1.0
  intl: ^0.18.1

# package_info_plus (temporarily override for chewie)
dependency_overrides:
  wakelock:
    git:
      url: https://github.com/diegotori/wakelock.git
      ref: main
      path: wakelock/
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock.git
      ref: main
      path: wakelock_windows/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
