name: flutter_leaf_manager
description: A new Flutter package project.
version: 1.9.37-dev
publish_to: 'none'
homepage: https://github.com/JosephNK/flutter_leaf_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  path_provider: ^2.1.3

  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  app_tracking_transparency: ^2.0.5
  flutter_app_badger: ^1.5.0

  share_plus: ^9.0.0
  url_launcher: ^6.2.6

  android_id: ^0.3.6

  flutter_leaf_common:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.37-dev'
      path: ./packages/leaf_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
